volumes:
  postgres_data: {}

services:
  postgres:
    container_name: ai-trainer.db
    image: postgres:17-alpine
    ports:
      - 5560:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ai_trainer
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
